### ISSUE TITLE
Adding demo mode to LL Practice

### ISSUE THREAD

**Issue by KCFindstr** [yjhatfdu/NGLLP#2]
希望能增加一个自动演示模式便于欣赏谱面以及练习。
我尝试通过Tampermonkey脚本模拟点击，但是由于不知道如何获取当前歌曲播放时间以及谱面所以没法做到演示效果。
另外，search API 502了希望能解决。

**Comment by yjhatfdu** [comment]
搜索已经修复，自动播放模式是不会支持的，这个很久以前就已经详细讨论过了
